# @package _global_
defaults:
  - /env/inversion/path_follower
  - /opt/masked_mimic/inversion/base

algo:
  config:
    models:
      extra_input_obs_size: ${env.config.path_follower_params.path_obs_size}