# @package _global_

steering_obs_size: 3 # same as steering task

steering_units: [ 256, 256 ]

env_params:
  steering_obs_size: ${steering_obs_size}
  steering_units: ${steering_units}

steering_for_transformer_model:
  _target_: phys_anim.agents.models.mlp.MLP_WithNorm
  config:
    initializer: ${actor_initializer}
    units: ${steering_units}
    activation: ${actor_activation}
    use_layer_norm: ${actor_use_layer_norm}
    normalize_obs: ${normalize_obs}
    obs_clamp_value: ${obs_clamp_value}
    encoder_input_dim: ${steering_obs_size}
    operations:
      - type: encode
      - type: reshape
        new_shape:
          - batch_size
          - 1
          - ${steering_for_transformer_model.num_out}
  num_in: ${steering_obs_size}
  num_out: ${transformer_preprocessor.config.latent_dim} # don't touch

transformer_preprocessor:
  config:
    extra_inputs:
      steering_obs: ${steering_for_transformer_model}

algo_extra_inputs:
  steering_obs:
    retrieve_from_env: True
    dtype: float
    size: ${steering_model.num_in}
