# @package _global_

defaults:
  - /algo: amp
  - /terrain/terrain_obs
  - /terrain/complex
  - /scenes/samp
  - /opt/save_best_reward_model
  - /opt/single_gpu

motion_file: phys_anim/data/motions/smpl_humanoid_walk.npy
scene_lib: null

env:
  config:
    mimic_reset_track:
      reset_on_episode_reset: False
      reset_episode_on_reset_track: False
    enable_height_termination: True

experiment_name: amp_inversion

wandb:
  wandb_group: amp
  wandb_tags: [ amp ]




