# @package _global_

defaults:
  - masked_mimic
  - /opt/masked_mimic/inversion/steering
  - /opt/clear_critic
  - /opt/clear_extra_inputs
  - /terrain/terrain_obs
  - /opt/masked_mimic/historical_pose_obs
  - /opt/masked_mimic/steering
  - /algo/ppo_finetune

name: masked_mimic_inversion_steering_ppo_finetune

env:
  config:
    task_reward_w: 1.0

algo:
  config:
    dagger:
      only_bc: False
      bc_coeff: 0

    models:
      # Append the steering obs to the actor and critic inputs
      steering_model:
        _target_: phys_anim.agents.models.common.Flatten
        config:
          normalize_obs: False
          obs_clamp_value: null
        # Input and output size are the same due to flattening
        num_in: ${env.config.steering_params.obs_size}
        num_out: ${env.config.steering_params.obs_size}

      steering_model_for_transformer:
        _target_: phys_anim.agents.models.mlp.MLP_WithNorm
        config:
          initializer: ${algo.config.actor.config.initializer}
          units: ${algo.config.models.prior_preprocessor_units}
          activation: ${algo.config.actor.config.activation}
          use_layer_norm: ${algo.config.actor.config.use_layer_norm}
          normalize_obs: ${algo.config.normalize_obs}
          obs_clamp_value: ${algo.config.obs_clamp_value}
          encoder_input_dim: ${env.config.steering_params.obs_size}
          operations:
            - type: encode
            - type: reshape
              new_shape:
                - batch_size
                - 1
                - ${algo.config.models.motion_text_embeddings_for_transformer_model.num_out}
        num_in: ${env.config.steering_params.obs_size}
        num_out: ${algo.config.actor.config.mu_model.config.transformer_token_size}

      prior_pre_processor:  # Transformer inputs
        config:
          extra_inputs:
            steering_obs: ${algo.config.models.steering_model_for_transformer}

    critic:
      _target_: phys_anim.agents.models.critic.CriticMLP
      _recursive_: False
      config:
        initializer: default
        units: [1024, 1024, 1024]
        activation: relu
        normalize_obs: ${algo.config.normalize_obs}
        obs_clamp_value: ${algo.config.obs_clamp_value}
        use_layer_norm: False
        extra_inputs:
          steering_obs: ${algo.config.models.steering_model}

    extra_inputs:
      steering_obs:
        retrieve_from_env: True
        dtype: float
        size: ${algo.config.models.steering_model.num_in}

vae_latent_from_prior: True
vae_noise_type: zeros
