# @package _global_

defaults:
  - masked_mimic
  - /opt/clear_critic
  - /opt/masked_mimic/inversion/steering
  - /algo/masked_mimic_finetune

experiment_name: masked_mimic_inversion_steering_and_current_pose

algo:
  config:
    models:
      extra_input_obs_size: ${eval:${env.config.steering_params.obs_size}+${robot.self_obs_max_coords_size}}
env:
  config:
    steering_params:
      use_current_pose_obs: True