# @package _global_
env:
  config:
    masked_mimic_masking:
      joint_masking:
#        masked_mimic_fixed_conditioning: True
        masked_mimic_repeat_mask_probability: 1.
        time_gap_mask_min_steps: 1000
        time_gap_mask_max_steps: 1001
        with_conditioning_max_gap_probability: 0.
        masked_mimic_time_gap_probability: 1.